### ISSUE TITLE
Activity Log

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/provider-dashboard#132]
![Image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/25018f8e-9e3f-40ba-94cf-f99879949571)

- [ ] Design from mocks
- [ ] Data from "Current Transaction Status"
- [ ] Show the blockhash under the log if there is one
- [ ] Overflow should scroll 
- [ ] Newest event on top

dev details
- [ ] Activity log store [array]
- [ ] Keep tx status intact and we will evaluate at the end

nice to have
- [ ] Nice to have: New events can be green or red text with a fade to normal over a few ms

**Comment by claireolmstead** [comment]
Dev Notes: 
- Consider creating an events listener like `listenToEvents` in the file below.
https://github.com/AmplicaLabs/access-continuous-testing/blob/main/tests/utils/frequency.ts

**Comment by rlaferla** [comment]
With an _event listener design_, code is centralized to mostly if not entirely the `ActivityLog` component and connection status can be logged automatically.  With a _store design_, each activity that needs to be logged has to be coded per component.  Either design would work well but the event listener one may be better.
