### ISSUE TITLE
Cannot access "buffer.Buffer" in client code. 

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/provider-dashboard#141]
The browser console issues this warning:

`Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.`

To fix:

https://stackoverflow.com/questions/73353392/cannot-access-buffer-buffer-in-client-code-svelte-with-userbase

**Comment by wilwade** [comment]
Not seeing this anymore
