### ISSUE TITLE
As a potential provider, if choose mainnet, I would like a way to email Frequency Council to request to become a provider

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/provider-dashboard#26]
As a potential provider, if choose mainnet, I would like a way to email Frequency Council to request to become a provider.

Until we have verbiage from the design team we can add some filler text..
"If you would like to be a provider on mainnet, please reach out directly to us at hello@frequency.xyz"

This can just be a simple mailto: link

Parent issue https://github.com/LibertyDSNP/provider-dashboard/issues/21

**Comment by shannonwells** [comment]
There's a mailto link as of #43
