### ISSUE TITLE
Activity Log Improvements

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/provider-dashboard#42]
As a Provider in the Activity Log:
1. If my transaction fails, I don't want to _have_ to go the explorer to see what went wrong. I would like the failure reason to appear and be understandable.
2. However I may want to go to the Polkadot UI for something, so I'd still like to see a link to my chosen network and maybe also to the block of the last transaction.
3. I also want the block and epoch to stay updated.

**Comment by wilwade** [comment]
Future work
