### ISSUE TITLE
Can we control whether the extension asks to access the camera

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/provider-dashboard#51]
# Camera access issue?
Figure out why only _sometimes_ the extension will ask to access the camera and if we can 
1. control that
2. and/or explain _to users_ why it wants the camera access so they are not surprised or suspicious.

It does not occur on deployed version.  It does appear to happen when running a local dev version.

**Comment by rlaferla** [comment]
It likely uses the camera to scan the QR barcode from the Parity Vault mobile app to sign transactions.

**Comment by shannonwells** [comment]
It definitely uses the camera for that purpose, however the question is how/when it does ask, because it does not always do so as mentioned in the description.  I will update.

**Comment by rlaferla** [comment]
Do you have any screenshots of the prompt (and underlying page/screen) asking the user for camera access?  It would help understand the context to see it visually.
