### ISSUE TITLE
Provider Log in page

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/provider-dashboard#72]
The goal of this is to create this state and refactor what we have now 

![Screenshot 2024-01-10 at 2 42 58 PM](https://github.com/LibertyDSNP/provider-dashboard/assets/444888/60cc5642-3432-4ad5-bd60-d01ab73c0543)

Not in the mocks

- local node connection 
- error handling 

Notes
- Become a provider doesn't need to link yet
- Needs styling from #62 
- Dep of #92 

Checklist: @claireolmstead @rlaferla 
 

- [ ] ....
- [ ] .....

**Comment by wilwade** [comment]
Moved to issue https://github.com/LibertyDSNP/provider-dashboard/issues/90
