### ISSUE TITLE
Implement Components including Theme And Copy

### ISSUE THREAD

**Issue by claireolmstead** [LibertyDSNP/provider-dashboard#81]
- [x] #90 
- [x] #91
- [x] #83
- [x] #108 
- [x] #84
- [x] #85
- [x] #86
- [x] #87
- [x] #88

** Activity Log in different Story.

Dev Notes:
- Create as much reusable code as possible. So much of the styling in the above blocks overlaps.

**Comment by wilwade** [comment]
Completed!
