### ISSUE TITLE
`Connect Provider` modal

### ISSUE THREAD

**Issue by claireolmstead** [LibertyDSNP/provider-dashboard#86]
![Image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/6cf90348-44b2-40f8-8fb8-2d49f9145cfb)

![Image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/3d7e6f61-fb9e-4770-a6ad-ff2cd90e4711)

## Acceptance Criteria
- Should pop up when you press the icon in the top right
- Should act the same as the login
- Should be able to click outside of the black box to cancel
- Should prefill with the current network and control key

Blockers
- #106

**Comment by claireolmstead** [comment]
Note: icon changed to make more clear that it's not a refresh, but a switch.

**Comment by rlaferla** [comment]
This depends on a prerequisite of: https://github.com/LibertyDSNP/provider-dashboard/issues/106

**Comment by rlaferla** [comment]
![Image](https://github.com/LibertyDSNP/provider-dashboard/assets/1135694/794cdb62-a548-4931-bd12-254528a0850a)

**Comment by claireolmstead** [comment]
Due to blockers, going to merge this story in with open TODOs. TODOs to be resolved in #113
