### ISSUE TITLE
`Stake to provider`

### ISSUE THREAD

**Issue by claireolmstead** [LibertyDSNP/provider-dashboard#87]
![Image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/ac9949fd-c55f-43c5-9726-d2828a1cec92)

## Acceptance Criteria
- Should act like our standard modal

**Comment by rlaferla** [comment]
Question:
The title "Amount in Unit" is that literal or is the unit dynamic?  e.g.  "Amount in XRQCY"

**Comment by rlaferla** [comment]
Question:

Which keys can the user stake from?   1.  Any key?  2.  Any key associated with a MSA?  3.  Any provider key?  4.  Only the key the user is signed in as?  5.  Other

**Comment by rlaferla** [comment]
@wilwade ☝🏻

**Comment by wilwade** [comment]
@rlaferla 

> Which keys can the user stake from? 1. Any key? 2. Any key associated with a MSA? 3. Any provider key? 4. Only the key the user is signed in as? 5. Other

Any key.

**Comment by rlaferla** [comment]
In addition to my previous comment, should the unit in the requirements section be updated dynamically:  "1. Ensure the control key has a FRQCY balance."?

**Comment by wilwade** [comment]
It already is, so it should remain so.

**Comment by rlaferla** [comment]
It is already hard-coded?  Please clarify because from what I see in the source code, it's hard-coded:

```
<ol class="ml-4 mt-4 list-decimal font-light">
      <li>Ensure the control key has a FRQCY balance.</li>
      <li>Click 'Stake'</li>
      <li>This will require 1 signature to send the transaction.</li>
</ol>
```

**Comment by wilwade** [comment]
Rococo:
![image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/f2f35dd0-e964-469b-a728-6b36a82750f0)

Localhost:
![image](https://github.com/LibertyDSNP/provider-dashboard/assets/1252199/3303fa84-1614-41df-a9c7-5f545379b8e1)

**Comment by wilwade** [comment]
Complete!
